service: rubyvideo

image: adrienpoly/rubyvideo

servers:
  - 91.107.208.207

registry:
  username: adrienpoly
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RUBY_YJIT_ENABLE: 1
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 3
  secret:
    - RAILS_MASTER_KEY
    - APPSIGNAL_PUSH_API_KEY
    - MEILI_MASTER_KEY
    - RUBYVIDEO_GITHUB_TOKEN
ssh:
  user: root
volumes:
  - "storage:/rails/storage"
accessories:
  search:
    image: getmeili/meilisearch:v1.1
    host: 91.107.208.207
    port: 7700
    env:
      clear:
        --http-addr: localhost:7700
        --env: production
        --db-path: storage/meilisearch
        --no-analytics: true
        --dump-dir: storage/meilisearch/dumps
        --max-indexing-memory: 2Gb
        --snapshot-dir: storage/meilisearch/snapshots
      secret:
        - MEILI_MASTER_KEY
    volumes:
      - "storage:/rails/storage"

builder:
  cache:
    type: registry
    options: mode=max,image-manifest=true,oci-mediatypes=true
